package com.assignment.testrest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Request implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String pid;

	public Request() {
	}

	public java.lang.String getPid() {
		return this.pid;
	}

	public void setPid(java.lang.String pid) {
		this.pid = pid;
	}

	public Request(java.lang.String pid) {
		this.pid = pid;
	}

}